### ISSUE TITLE
Avoid unnamed columns

### ISSUE THREAD

**Issue by krlmlr** [dmenne/breathtestcore#1]
`cleanup_data()` calls `dplyr::distinct()` on a (deliberately) unnamed data frame in one of the tests. At some point *dplyr* will stop accepting such broken data frames and/or call `tibble::repair_names()` and talk loudly about it (https://github.com/tidyverse/dplyr/issues/3424). Until then it is advisable to ensure that the input to a *dplyr* verb is a well-formed data frame.

I'll make sure that `distinct()` keeps supporting unnamed data frames in *dplyr* 0.7.5.

**Comment by dmenne** [comment]
Please give me a hint what branch to use. I tried with current github dplyr and there was no problem. 

Do I understand that things should be fine when I call tidy_names before distinct?

**Comment by krlmlr** [comment]
I got a failure with the current master of dplyr when running the tests in the current master of breathtestcore.

**Comment by dmenne** [comment]
Could not see it, but maybe this works

https://github.com/dmenne/breathtestcore

https://travis-ci.org/dmenne/breathtestcore

**Comment by krlmlr** [comment]
Thanks, this should do the job.
